=== TarikDjebienBachelor/NAW/XML/TPs/TP1_XML/Exercice2/recette.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT recette (nom, portion, preparation, cuisson, repos?, ingredients, guide)>

<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom
             id ID #IMPLIED
>

<!ELEMENT portion (#PCDATA)>

<!ELEMENT preparation EMPTY>
<!ATTLIST preparation 
             value CDATA #REQUIRED
             unit  (min|h) #REQUIRED
>

<!ELEMENT cuisson EMPTY> 
<!ATTLIST cuisson
             value CDATA #REQUIRED
             unit  (min|h) #REQUIRED
>

<!ELEMENT repos EMPTY>
<!ATTLIST repos
             value CDATA #REQUIRED
             unit  (min|h) #REQUIRED
>

<!ELEMENT ingredients (i+)>

<!ELEMENT i (nom,nbre?,poids?)>

<!ELEMENT nbre (#PCDATA)>

<!ELEMENT poids (#PCDATA)>
<!ATTLIST poids
             unit (gramme) #REQUIRED
>

<!ELEMENT guide (#PCDATA|block|renvoi)*>

<!ELEMENT block (#PCDATA|renvoi|strong|repos)*>

<!ELEMENT renvoi (#PCDATA)> 
<!ATTLIST renvoi
             ref IDREF #REQUIRED
>

<!ELEMENT strong (#PCDATA)>

=== TarikDjebienBachelor/NAW/XML/TPs/TP1_XML/Exercice2/recette.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE recette SYSTEM "recette.dtd">
<recette>
  <nom> Tiramisu </nom>
  <portion> 6/8 </portion>
  <preparation value="35" unit="min"/>
  <cuisson value="0" unit="min"/>
  <repos value="12" unit="h"/>
  <ingredients>
    <i><nom id="ing1"> oeufs </nom> <nbre>5</nbre></i>
    <i><nom id="ing2"> sucre en poudre </nom> <poids unit="gramme">100</poids></i>
    <i><nom id="ing3">mascarpone</nom><poids unit="gramme">500</poids></i>
    <i><nom id="ing4">cafe soluble</nom><poids unit="gramme">25</poids></i>
    <i><nom id="ing5">biscuits a la cuillere</nom><nbre>42</nbre></i>
    <i><nom id="ing6">cacao non sucre </nom><poids unit="gramme">10</poids></i>
  </ingredients>
  <guide>
    <block>
      Commencez par separer les 5 jaunes d’<renvoi ref="ing1">oeufs</renvoi> 
      de leur blanc dans deux grands saladiers et montez les 5 blancs 
      d’<renvoi ref="ing1">oeufs</renvoi> en neige tres fermes.
    </block>
    <block>
      Battez les 5 jaunes avec le <renvoi ref="ing2">sucre</renvoi>
      jusqu’a l’obtention d’un melange mousseux, puis ajoutez-y le
      <renvoi ref="ing3">mascarpone</renvoi>.
    </block>
    <block>
      Incorporez a present les blancs d’oeufs dans le melange.
    </block>
    <block>
      Preparez un cafe bien fort avec du <renvoi ref="ing4">cafe soluble</renvoi> 
      et trempez-y les <renvoi ref="ing5">biscuits</renvoi> au fur et a mesure de leur installation dans le plat.
      <strong>Attention les biscuits absorbent tres vite le cafe.</strong>
    </block>
    <block>
      Commencez par disposer une couche de biscuits imbibes au fond du
      moule, puis versez une couche de m ́lange et ainsi de suite.
    </block>
    <block>
      Saupoudrez le cacao sur le tiramisu en utilisant une petite
      passoire. Il sera ainsi plus facile de le parsemer
      uniformement.
    </block>
    <block>
      Il ne vous reste plus qu’a le placer au refrigerateur durant
      <repos value="12" unit="h"/> heures.
    </block>
  </guide>
</recette>
